apiVersion: v1
kind: ServiceAccount
metadata:
  name: bacnet-snoop
  namespace: azure-iot-operations
---
apiVersion: v1
kind: Pod
metadata:
  name: bacnet-snoop
  namespace: azure-iot-operations
spec:
  serviceAccountName: bacnet-snoop
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - image: eastlake.azurecr.io/bacnet-snoop:latest
    name: bacnet-snoop
    env:
    - name: SNOOP_INTERFACE
      value: "enp0s13f0u4c2"
    - name: BACNET_IFACE
      value: "enp0s13f0u4c2"
    securityContext:
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]
    volumeMounts:
    - name: broker-sat
      mountPath: /var/run/secrets/tokens
    - name: trust-bundle
      mountPath: /var/run/certs
  volumes:
  - name: broker-sat
    projected:
      sources:
      - serviceAccountToken:
          path: broker-sat
          audience: aio-internal
          expirationSeconds: 86400
  - name: trust-bundle
    configMap:
      name: azure-iot-operations-aio-ca-trust-bundle
